packages:
  - packages/*
  - playground
  - plugins/*
  - website
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.8.0+sha512-CuwFoo5l+6m6PRF3uEUg8VqUkYlf9IPbDOHGU/xbBRW7OPbocs4JSMqfwcj+CEQJP9YH6+QSxAb4zsGlX3SeCA==
  "@savvy-web/pnpm-plugin-silk": 0.36.0+sha512-k5sHGnJ4SUk1iDzIUV6qWbJAquJl3LIEHKEKPQyrqge5h2Hr3xvCHGH3n0AcBNuGTp4cf4YESrOg0/YKXWhZ1w==
linkWorkspacePackages: deep
verifyDepsBeforeRun: false
